altered lint config

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -21,4 +21,4 @@ jobs:
                 pip install -r requirements.txt
 
             - name: Run Ruff
-              run: ruff . || { echo 'Ruff failed'; exit 1;}
+              run: ruff check . || { echo 'Ruff failed'; exit 1;}
